## Numpy: La potencia del arreglo

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1280px-NumPy_logo.svg.png" style="width:400px;height:150px;">

La librería Numpy (https://numpy.org/) permite la inclusión del objeto `Array` para hacer operaciones de tipo vectorial, es decir, donde los elementos de los objetos operan entre si:

In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
B = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Operacion entre arreglo del mismo tamaño
print(A + B)

[11 22 33 44 55 66 77 88 99]


In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([1, 2, 3])

# Operacion entre arreglo del distinto tamaño (broadcast)
print(A**B)

[[  1   4  27]
 [  4  25 216]
 [  7  64 729]]


### Generación de arreglos

In [4]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.logspace(0, 1, 10)

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [7]:
np.empty(5, dtype=np.int16)

array([257, 257, 257, 257, 257], dtype=int16)

In [8]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.eye(6, k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [13]:
np.diag(np.arange(0, 5,1.5))

array([[0. , 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. ],
       [0. , 0. , 3. , 0. ],
       [0. , 0. , 0. , 4.5]])

### Indexación de elementos

In [14]:
A = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(A)

[10 20 30 40 50 60 70 80 90]


In [15]:
A[3:6]

array([40, 50, 60])

In [16]:
A[2:9:2]

array([30, 50, 70, 90])

In [17]:
A[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

In [18]:
A = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(A)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [19]:
A[:,0]

array([10, 40, 70])

In [20]:
A[2:]

array([[70, 80, 90]])

In [21]:
A[[0,2],[0,2]]

array([10, 90])

### Dimensiones

In [22]:
A = np.random.randint(1, 25, (10))    # Vector
print(A)
print(A.shape)

[ 1 23 14 11 12 11 18 16 17  1]
(10,)


In [23]:
A = np.random.randint(1, 25, (1, 10))   # Arreglo
print(A)
print(A.shape)

[[ 9  7 19  7 16 11 18 21 11 17]]
(1, 10)


In [24]:
A = np.random.randint(1, 25, (10, 1))
print(A)
print(A.shape)

[[23]
 [20]
 [ 7]
 [22]
 [20]
 [16]
 [15]
 [11]
 [ 9]
 [12]]
(10, 1)


In [25]:
A = np.random.randint(1, 10, (3, 3)).flatten()    # -> Vector
print(A)

[7 5 6 3 6 8 5 7 7]


In [26]:
A = np.arange(1, 10).reshape(3, 3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
A = np.squeeze(np.random.randint(1, 25, (1, 10)))   # Elimina la dimension 1
print(A)
print(A.shape)

[10  6 12 22 20 10  2  3 15 18]
(10,)


In [28]:
A = np.array([0, 1, 2, 3, 4, 5]).reshape(3, 2)
B = np.array([6, 7, 8, 9, 10, 11]).reshape(3, 2)
print(A, '\n')
print(B, '\n')
np.concatenate([A, B])    # axis=0

[[0 1]
 [2 3]
 [4 5]] 

[[ 6  7]
 [ 8  9]
 [10 11]] 



array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
np.concatenate([A, B], axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [30]:
A = np.array([1, 2, 3, 4])
np.vstack([A, A, A])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [31]:
np.hstack([A, A, A])

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

Con la operación anterior se obtiene un resultado inseperado. Esto es por las dimensiones de A:

In [32]:
A.shape

(4,)

Podemos utilizar el método `np.newaxis` para agregarle una dimension adicional al arreglo para poder hacer el apilado, al aplicarlo a los indices:

In [33]:
A = A[:, np.newaxis]

In [34]:
np.hstack([A, A, A])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

### Funciones elemento-a-elemento

In [35]:
A = np.array([1, 2, 3, 4, 5])

In [36]:
np.log(A)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [37]:
np.log2(A)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [38]:
np.log10(A)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [39]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [40]:
np.abs(A)

array([1, 2, 3, 4, 5])

In [41]:
np.sin(A)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [42]:
np.cos(A)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [43]:
np.tan(A)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

### Funciones de agregación

In [44]:
A = np.random.normal(loc=0, scale=2.5, size=(100,))

In [45]:
np.sum(A)

44.4142109118436

In [46]:
np.median(A)

0.5352387352719692

In [47]:
np.mean(A)

0.444142109118436

In [48]:
np.var(A)

6.2767605377698565

In [49]:
np.std(A)

2.5053463907751072

In [50]:
np.min(A)

-6.051483443224549

In [51]:
np.max(A)

5.992052021133421

In [52]:
np.argmin(A)

64

In [53]:
np.argmax(A)

58

### Indexación booleana y expresiones condicionales

In [54]:
A = np.random.randint(1, 50, (100))
print(A)

[ 1 46 19 17 17 44 25 12  1 38 36  4 12 27  1 19 33 18 37 47 22 18 14 27
 10 13 22 46  4  8 25 19 45 19 12 34 10 37 11  4 10 11 19 34 26 19 31 47
 20 12 20 25 46 43 23 33  7  2 36 40 15 42 11 30 37 21 26 32 48  8 25 34
 38  2 12 45 39 39 36  1 33 41 13 37 49 36  5 25 12 25 17 28 26  7 23 18
 45 33 41 22]


In [55]:
A[A % 3 == 0]

array([12, 36, 12, 27, 33, 18, 18, 27, 45, 12, 12, 33, 36, 15, 42, 30, 21,
       48, 12, 45, 39, 39, 36, 33, 36, 12, 18, 45, 33])

In [56]:
A[A % 3 == 0] = A[A % 3 == 0] - A[A % 3 == 0]
print(A)

[ 1 46 19 17 17 44 25  0  1 38  0  4  0  0  1 19  0  0 37 47 22  0 14  0
 10 13 22 46  4  8 25 19  0 19  0 34 10 37 11  4 10 11 19 34 26 19 31 47
 20  0 20 25 46 43 23  0  7  2  0 40  0  0 11  0 37  0 26 32  0  8 25 34
 38  2  0  0  0  0  0  1  0 41 13 37 49  0  5 25  0 25 17 28 26  7 23  0
  0  0 41 22]


In [57]:
np.where(A == 0)

(array([ 7, 10, 12, 13, 16, 17, 21, 23, 32, 34, 49, 55, 58, 60, 61, 63, 65,
        68, 74, 75, 76, 77, 78, 80, 85, 88, 95, 96, 97], dtype=int64),)

In [58]:
np.where(A == 0, 'A', ' ')    # dtype='<U1' : Unicode 1-char left aligned

array([' ', ' ', ' ', ' ', ' ', ' ', ' ', 'A', ' ', ' ', 'A', ' ', 'A',
       'A', ' ', ' ', 'A', 'A', ' ', ' ', ' ', 'A', ' ', 'A', ' ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', 'A', ' ', 'A', ' ', ' ', ' ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'A', ' ', ' ',
       ' ', ' ', ' ', 'A', ' ', ' ', 'A', ' ', 'A', 'A', ' ', 'A', ' ',
       'A', ' ', ' ', 'A', ' ', ' ', ' ', ' ', ' ', 'A', 'A', 'A', 'A',
       'A', ' ', 'A', ' ', ' ', ' ', ' ', 'A', ' ', ' ', 'A', ' ', ' ',
       ' ', ' ', ' ', ' ', 'A', 'A', 'A', ' ', ' '], dtype='<U1')

In [59]:
A = np.arange(1, 11)
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
np.select([A % 2 == 0, A % 2 != 0], [A * 2, A / 2])

array([ 0.5,  4. ,  1.5,  8. ,  2.5, 12. ,  3.5, 16. ,  4.5, 20. ])

In [61]:
np.choose([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], [A * 2, A / 11])

array([ 2.        ,  4.        ,  6.        ,  8.        , 10.        ,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

### Operaciones de conjuntos

In [62]:
A = np.unique(np.random.randint(1, 25, (50,)))
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18 19 20 21 22 23 24]


In [63]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 9])
B = np.array([2, 4, 6, 8])

np.intersect1d(A, B)

array([2, 4, 6])

In [64]:
np.union1d(A, B)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.setdiff1d(A, B)

array([1, 3, 5, 7, 9])

### Operaciones matriciales

In [66]:
A = np.matrix([[1, 2, 3], [4, 5, 6]])
B = np.matrix([[1, 2], [3, 4], [5, 6]])
print(A, '\n')
print(B, '\n')

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]] 



In [67]:
A = np.matrix('1, 2, 3; 4, 5, 6')
B = np.matrix('1, 2; 3, 4; 5, 6')
print(A, '\n')
print(B, '\n')

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]] 



In [68]:
A * B

matrix([[22, 28],
        [49, 64]])

In [69]:
np.matrix.dot(A, B)

matrix([[22, 28],
        [49, 64]])

In [70]:
A.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [71]:
A.I

matrix([[-0.94444444,  0.44444444],
        [-0.11111111,  0.11111111],
        [ 0.72222222, -0.22222222]])

In [72]:
np.linalg.det(np.matrix('2, 3; 6, 9'))

0.0

### Ejemplo de aplicación: algebra lineal
Calcule el voltaje entre los extremos de la resistencia en el siguiente circuito:
![](https://dademuchconnection.files.wordpress.com/2019/11/null-27.png?w=1086)

Resolvamos el circuito por el método de mallas:

$$ (R_1 + R_2 + R_3) * i_1(t) - R_2 * i_2(t) - R_3 * i_3(t) = V_2 $$
$$ -R_2 * i_1 + (R_2 + R_6) * i_2(t) + 0 * i_3(t) = 0$$
$$ -R_3 * i_1(t) + 0 * i_2(t) + (R_3 + R_4 + R_5) * i_3(t) = V_1 $$


In [73]:
R1, R2, R3, R4, R5, R6 = 100, 820, 680, 1500, 220, 1000
V1, V2 = 15, 12

A = np.matrix([[R1 + R2 + R3, -R2, -R3], [ -R2, R2 + R6, 0], [-R3, 0, R3 + R4 + R5]])
B = np.matrix([[V2], [0], [V1]])
I = A.I * B

print(I)

[[0.01565687]
 [0.0070542 ]
 [0.01068611]]


### Ejemplo de aplicación: arreglos 2D
La temperatura de sensación o, mejor, temperatura percibida, es un índice que sirve para evaluar la sensación térmica que experimenta un cuerpo humano bajo los efectos combinados de la temperatura y de la velocidad del viento. Se calcula con la siguiente fórmula:

$$ T_{s}=13,12+0,6215\cdot T-11,37\cdot V^{0,16}+0,3965\cdot T\cdot V^{0,16} $$ 

Calcule el valor de sensación térmica en el rango de velocidades de viento de 10 a 80 km/h en pasos de 10 km/h, y temperaturas entre 40° y 10° en pasos de 5° para obtener una tabla en donde las filas sean las velocidades y las columnas las temperaturas.

In [76]:
import pandas as pd
from IPython.display import HTML

V = np.arange(10, 90, 10)
T = np.arange(40, 9, -5)

tab = np.empty((V.size, T.size))   # Arreglo base a llenar
for idx, vel in enumerate(V):
    T_col = 13.12 + 0.625 * T - 11.37 * vel**0.16 + 0.396 * T * vel**0.16
    tab[idx,:] = T_col.squeeze()
       
print("{:^72}".format("Sensación Térmica (Vel Viento x Temperatura)"))
print("=" * 72)

df = pd.DataFrame(tab, 
                  index=[str(v) + ' km/h' for v in V], 
                  columns=[str(t) + '°C' for t in T])
df     # _repr_html_ : df.to_html()

              Sensación Térmica (Vel Viento x Temperatura)              


40°C       35°C       30°C       25°C       20°C       15°C  \
10 km/h  44.581116  38.594145  32.607174  26.620204  20.633233  14.646262   
20 km/h  45.338922  39.016278  32.693635  26.370992  20.048349  13.725706   
30 km/h  45.822770  39.285805  32.748840  26.211874  19.674909  13.137944   
40 km/h  46.185608  39.487923  32.790237  26.092552  19.394866  12.697181   
50 km/h  46.478777  39.651231  32.823686  25.996141  19.168595  12.341050   
60 km/h  46.726206  39.789061  32.851916  25.914771  18.977626  12.040482   
70 km/h  46.941109  39.908772  32.876435  25.844098  18.811761  11.779424   
80 km/h  47.131600  40.014885  32.898169  25.781454  18.664738  11.548022   

             10°C  
10 km/h  8.659291  
20 km/h  7.403063  
30 km/h  6.600979  
40 km/h  5.999495  
50 km/h  5.513504  
60 km/h  5.103337  
70 km/h  4.747087  
80 km/h  4.431307